version: '3.7'
services:
  event-mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongo-event-data-dev:/data/db
    container_name: event-mongo
    environment:
       MONGO_PORT: 27017
       MONGO_INITDB_ROOT_USERNAME: maple
       MONGO_INITDB_ROOT_PASSWORD: maple
       MONGO_INITDB_DATABASE: maple-event-db
  auth-mongo:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - mongo-data-dev:/data/db
    container_name: 'auth-mongo'
    environment:
       MONGO_PORT: 27017
       MONGO_INITDB_ROOT_USERNAME: maple
       MONGO_INITDB_ROOT_PASSWORD: maple
       MONGO_INITDB_DATABASE: maple-db

volumes:
  mongo-data-dev:
  mongo-event-data-dev:
