### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "TEST",
  "password": "TESTPASS"

}

###

POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"

}

###
GET http://localhost:3001/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiNjgyNzRkZjJlNTU3Y2UwOWM3MDhlOGE1Iiwicm9sZXMiOlsiQURNSU4iLCJPUEVSQVRPUiIsIlVTRVIiLCJBVURJVE9SIl0sImlhdCI6MTc0NzQ4NTczMCwiZXhwIjoxNzQ3NDg5MzMwfQ.B2GGWmDEf0CnjUMPPppNSYhX1K_gFS_xHAxDYsh5s84

###
GET http://localhost:3000/users/TEST
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiNjgyNzRkZjJlNTU3Y2UwOWM3MDhlOGE1Iiwicm9sZXMiOlsiQURNSU4iLCJPUEVSQVRPUiIsIlVTRVIiLCJBVURJVE9SIl0sImlhdCI6MTc0NzQ2OTcwMSwiZXhwIjoxNzQ3NDczMzAxfQ.6ljkhYqoDS5_Nc-jioWFJhPqU1ZoMPBcoa6UTrysfgE

###
PUT http://localhost:3000/users/TEST/roles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiNjgyNzRkZjJlNTU3Y2UwOWM3MDhlOGE1Iiwicm9sZXMiOlsiQURNSU4iLCJPUEVSQVRPUiIsIlVTRVIiLCJBVURJVE9SIl0sImlhdCI6MTc0NzQ2OTcwMSwiZXhwIjoxNzQ3NDczMzAxfQ.6ljkhYqoDS5_Nc-jioWFJhPqU1ZoMPBcoa6UTrysfgE

{
  "roles": ["USER"]
}