###

POST http://localhost:3000/auth-service/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiNjgyYWJhYzVjNzYyOWZmNTBhNWE2NTRlIiwicm9sZXMiOlsiQURNSU4iXSwiaWF0IjoxNzQ3NjQyMDM5LCJleHAiOjE3NDc2NDU2Mzl9.bfA1q1MA-5-zMeW1877c95bvEfbmkUkv6ILWV_UnNzE

{
  "username": "testtest",
  "password": "testtest"

}

###

GET http://localhost:3000/auth-service/users/testtest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiNjgyYWJhYzVjNzYyOWZmNTBhNWE2NTRlIiwicm9sZXMiOlsiQURNSU4iXSwiaWF0IjoxNzQ3NjQyMDM5LCJleHAiOjE3NDc2NDU2Mzl9.bfA1q1MA-5-zMeW1877c95bvEfbmkUkv6ILWV_UnNzE

###
GET http://localhost:3003/auth-service/users/me
Content-Type: application/json
Authorization: Bearer {{user}}

###
POST http://localhost:3003/event-service/events
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "name": "테스트",
  "condition": {
    "type": "test",
    "days": 7
  },
  "startDate": "2025-05-15",
  "endDate": "2028-05-15"
}
###
PUT http://localhost:3003/event-service/events/6828a8e59802de60b384dff2
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "name": "공노목",
  "condition": {
    "loginStreak": 9
  }
}

###
GET http://localhost:3003/event-service/events/6828a8e59802de60b384dff2
Content-Type: application/json
Authorization: Bearer {{admin}}


###
POST http://localhost:3003/event-service/rewards
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "eventId": "6829af53b06aaf3805d9a48c",
  "name": "TEST_REWARDS",
  "type": "POINT",
  "details": {
    "POINT": 100
  },
  "quantity": 55
}

###
GET http://localhost:3003/event-service/rewards
Content-Type: application/json
Authorization: Bearer {{admin}}