### Login to Admin
POST http://localhost:3000/auth-service/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"

}

### Create Event
POST http://localhost:3000/event-service/events
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "name": "테스트",
  "condition": {
    "type": "test",
    "days": 7
  },
  "startDate": "2025-05-15",
  "endDate": "2028-05-15"
}

### Update Event
PUT http://localhost:3000/event-service/events/6829daca181a450c46e2620a
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "name": "공노목",
  "condition": {
    "type": "loginStreak",
    "days": 9
  }
}

### Create REward
POST http://localhost:3000/event-service/rewards
Content-Type: application/json
Authorization: Bearer {{admin}}

{
  "eventId": "6829db0f181a450c46e2621a",
  "name": "TEST_REWARDS",
  "type": "POINT",
  "details": {
    "POINT": 100
  },
  "quantity": 55
}

### Login to User
POST http://localhost:3000/auth-service/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"

}

### Create Claim
POST http://localhost:3000/event-service/reward-claims
Authorization: Bearer {{user}}
Content-Type: application/json

{
  "eventId": "6829db0f181a450c46e2621a",
  "rewardId": "6829db2c181a450c46e26220"
}

### Get Claim Me
GET http://localhost:3000/event-service/reward-claims/me?eventId=6829db0f181a450c46e2621a
Authorization: Bearer {{user}}
Content-Type: application/json